module.exports = {
    de: {
        heroLabel: "Bilden, Halten, Aufrechterhalten",
        heroTitle: "Vollständige Lehrlingsausbildungen sparen Geld und Zeit",
        heroText: "Steigern Sie die Motivation und das Wissen Ihrer Lehrlinge mit Qizify!",
        heroButton: "Kontakt / Demo",
        textImageTitle: "Probleme mit unmotivierten Lehrlingen, die vorzeitig das Unternehmen verlassen?",
        textImageText1: "Steigern Sie die Begeisterung und das Fachwissen Ihrer Lehrlinge mit unserer Lösung für quizbasierte Prüfungsvorbereitung und Peer-to-Peer-Lernen.",
        textImageText2: "Unsere Tool verbessert Ihren interaktiven Onboarding-Prozess und erleichtert die individuelle berufliche Weiterentwicklung Ihrer Lehrlinge. Alles organisiert mit interaktiven und maßgeschneiderten Quiz, Karma-Punkten, Bestenlisten und detaillierten Lernanalysen für Ihre Lehrlinge und Mentoren!",
        benefitsTitle: "Vorteile für Ihr Unternehmen",
        benefits1Title: "Engagement und Treue",
        benefits1Text: "Qizify bindet Lehrlinge ein, verbessert ihr Wissen, fördert die Treue und reduziert gleichzeitig die Abbruchraten, wodurch die Investitionen des Unternehmens in Lehrlingsausbildungen maximiert werden.",
        benefits2Title: "Kosteneffizienz",
        benefits2Text: "Durch die Verhinderung vorzeitiger Abgänge spart unsere Lösung Unternehmen jährlich rund 18.000 € pro Lehrling und sichert langfristige Vorteile aus den Investitionen in die Lehrlingsausbildung.",
        benefits3Title: "Zeitersparnis",
        benefits3Text: "Unsere KI-gesteuerte Plattform optimiert die Erstellung von Quizfragen und gibt Mentoren mehr Zeit für andere wichtige Aufgaben, was letztendlich die Gesamtproduktivität steigert und das Unternehmenswachstum fördert.",
        benefits4Title: "Gamification",
        benefits4Text: "Gamification steigert die Motivation und das Engagement der Lernenden und bietet Pädagogen effektive Tools, um das Lernen interaktiver und unterhaltsamer zu gestalten.",
        benefits5Title: "Individuelles Lernen",
        benefits5Text: "Qizify passt Inhalte an Ihre Lehrlinge an, was das Verständnis und die Erinnerung verbessert und somit zu besseren Prüfungsergebnissen und der Entwicklung eines qualifizierten und sachkundigen Teams führt.",
        benefits6Title: "Umfassende Unterstützung",
        benefits6Text: "Qizify bietet umfassende Unterstützung für Mentoren, die alles von der Einarbeitung bis zur Prüfungsvorbereitung abdeckt und Lehrlinge mit den erforderlichen Fähigkeiten für ihr berufliches Wachstum in Ihrem Unternehmen ausstattet.",
        ctaTitle: "Nutzen Sie Qizify und revolutionieren Sie Ihre Lehrlingsausbildung.",
        ctaText: "Begleiten Sie uns bei der Schaffung von talentierten und motivierten Mitarbeitern für eine erfolgreiche Zukunft!",
        ctaButton: "E-MAIL SENDEN"
    },
    en: {
        heroLabel: "Educate, Retain, Sustain",
        heroTitle: "Complete Apprenticeships Saves You Money & Time",
        heroText: "Boost Engagement and Knowledge of Your Apprentices with Qizify!",
        heroButton: "Contact / Demo",
        textImageTitle: "Struggling with Unmotivated Apprentices Who Leave Company Prematurely?",
        textImageText1: "Elevate your apprentices’ enthusiasm and expertise with our solution for quiz-based exam preparation and peer-to-peer learning. ",
        textImageText2: "Our tool will enhance your interactive onboarding process and facilitate personalized professional upskilling for your apprentices. All organised with the interactive and tailored quizzes, Karma points, leaderboards and detailed learning analytics for both your apprentices and mentors!",
        benefitsTitle: "Benefits for Your Company",
        benefits1Title: "Engagement and Loyalty",
        benefits1Text: "Qizify engages apprentices, enhances their knowledge, fosters loyalty, and simultaneously reduces dropout rates, maximizing company investments in apprenticeships.",
        benefits2Title: "Cost-Efficiency",
        benefits2Text: "By preventing premature departures, our solution saves companies around €18,000 per apprentice annually and ensures long-term benefits from apprenticeship investments.",
        benefits3Title: "Time-Saving",
        benefits3Text: "Our AI-driven platform streamlines quiz creation, freeing up time for mentors to concentrate on other crucial tasks, ultimately boosting overall productivity and driving business growth.",
        benefits4Title: "Gamification",
        benefits4Text: "Gamification enhances engagement and motivation for learners while providing educators with effective tools to make learning more interactive and enjoyable.",
        benefits5Title: "Personalized Learning",
        benefits5Text: "Qizify tailors content to your apprentices, enhancing comprehension and retention, which in turn leads to improved exam results and the development of a skilled and knowledgeable team.",
        benefits6Title: "Comprehensive Support",
        benefits6Text: "Qizify provides comprehensive support for mentors, covering everything from onboarding to exam preparation, equipping apprentices with the essential skills required for their professional growth within your company.",
        ctaTitle: "Embrace Qizify and revolutionize your apprenticeship training.",
        ctaText: "Join us in creating a brighter, more engaged talents for a successful future!",
        ctaButton: "EMAIL US"
    }
};
