module.exports = {
    de: {
            st: "Schulen",
                shl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                sht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                shp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            ut: "Universitäten",
                uhl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                uht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                uhp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            ct: "Unternehmen",
                chl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                cht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                chp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            cst: "Coaches",
                cshl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                csht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                cshp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        },
    en: {
            st: "Schulen",
                shl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                sht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                shp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            ut: "Universitäten",
                uhl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                uht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                uhp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            c: "Unternehmen",
                chl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                cht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                chp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
            cst: "Coaches",
                cshl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                csht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                cshp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        }
};
