module.exports = {
    en: {            
            ct: "Unternehmen",
            chl: "Qizify Learning for companies",
            cht: "A dedicated platform for your employee's knowledge sharing, growth, peer-to-peer mentoring, and engagement.",
            chp: "",
                ct_feature1_Headline: "Peer-to-peer mentoring support",
                ct_feature1_Headline2: "Let specialists in your company learn from each other and feel that they belong!",
                ct_feature1_Text1: "Employees create quizzes based on their expertise and answer questions from colleagues on a topic, enabling them to benefit from specialists´ insights.",
                ct_feature1_Text1: "Finish a brown bad session with an entertaining quiz to identify how well your employees understood a topic!",
                ct_feature2_Headline: "Onboarding",
                ct_feature2_Headline2: "Create pre-onboarding quizzes to provide essential information about the company, its values, culture, policies, procedures, team introductions, product knowledge, compliance training, and more to your new employees before they join.",
                ct_feature2_Text1: "Qizify helps develop interactive quizzes for onboarding, covering orientation sessions and training modules, providing an engaging way for new employees to absorb necessary information. It accelerates onboarding and establishes a foundation for continuous learning and growth.",
                ct_feature3_Headline: "Upskilling",
                ct_feature3_Headline2: "Unlock the potential of your employees without external support!",
                ct_feature3_Text1: "Our platform allows your employees to identify the level of expertise in a topic and engages with quizzes aligned with their professional development goals, while your company fosters a culture of continuous learning. ",
                ct_other1_Headline: "Efficient Performance Analysis for Employee Growth",
                ct_other1_Text: "By understanding the strengths and weaknesses of their workforce, you can tailor your training programs to address specific needs, resulting in targeted skill development and improved overall performance.",
                ct_other2_Headline: "Enhance Employee Engagement and Motivation",
                ct_other2_Text: "By gamifying the learning experience, Qizify enhances employee engagement and motivation. Employees can earn Karma points through quiz verification by trainers or likes from their colleagues, creating a sense of achievement and friendly competition.",
                ct_other3_Headline: "Centralized Repository of Quizzes for Consistent Learning",
                ct_other3_Text: "Quizzes created by employees or trainers are automatically available to all other users, promoting knowledge sharing and standardization of learning materials. This helps companies maintain a cohesive learning environment and facilitates the seamless transfer of knowledge and skills.",
                ct_addon1: "Content generation is supported by AI-Assistant. Create relevant for your company quizzes 15 times faster!",
                ct_addon2: "5000 ready-made quizzes on hot topics (Leadership, cyber-security, programming, etc)",
                ct_addon3: "Higher security with SSO integration",
                ct_addon4: "Custom company branding at request",

            cst: "Coaches",
                cshl: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                csht: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
                cshp: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        },
    de: {   
            ct: "Unternehmen",
            cht: "Qizify Learning für Unternehmen",
            chp: "Eine dedizierte Plattform für den Wissensaustausch, das Wachstum, die Peer-to-Peer-Mentorenschaft und die Mitarbeiterbindung Ihrer Mitarbeiter.",
            ct_feature1_Headline: "Peer-to-Peer-Mentoring",
            ct_feature1_Headline2: "Lassen Sie Fachleute in Ihrem Unternehmen voneinander lernen und sich zugehörig fühlen!",
            ct_feature1_Text1: "Die Mitarbeiter erstellen Quizze basierend auf ihrem Fachwissen und beantworten Fragen ihrer Kollegen zu einem bestimmten Thema, wodurch sie von den Erkenntnissen der Experten profitieren.",
            ct_feature1_Text2: "Beenden Sie eine Besprechung oder Brown Bag Session mit einem unterhaltsamen Quiz, um zu überprüfen, wie gut Ihre Mitarbeiter ein Thema verstanden haben!",
            ct_feature2_Headline: "Onboarding",
            ct_feature2_Headline2: "Vor dem Einstieg neuer Mitarbeiter können Sie vorbereitende Quizze erstellen, die wichtige Informationen über Ihr Unternehmen, Werte, Kultur, Richtlinien, Teamvorstellungen, Produktkenntnisse, und mehr vermitteln.",
            ct_feature2_Text1: "Qizify ermöglicht interaktive Quizze für die Einführung, einschließlich Orientierung und Schulung. Ihre neue Mitarbeiter können so auf engagierte Weise die notwendigen Informationen aufnehmen. Dadurch beschleunigt sich die Einführung und es wird eine Grundlage für kontinuierliches Lernen und Wachstum geschaffen.",
            ct_feature3_Headline: "Weiterbildung",
            ct_feature3_Headline2: "Entfesseln Sie das Potenzial Ihrer Mitarbeiter ohne externe Unterstützung!",
            ct_feature3_Text1: "Qizify ermöglicht es Ihren Mitarbeitern, ihr Kompetenzniveau in einem Thema zu bestimmen und sich mit Quizzen zu beschäftigen, die auf ihre beruflichen Entwicklungsziele ausgerichtet sind, während Ihr Unternehmen eine Kultur des kontinuierlichen Lernens fördert.",

            ct_other1_Headline: "Effiziente Leistungsanalyse für das Wachstum Ihrer Mitarbeiter",
            ct_other1_Text: "Durch das Verständnis der Stärken und Schwächen Ihrer Belegschaft können Sie Ihre Schulungsprogramme an spezifische Bedürfnisse anpassen, was zu gezielter Kompetenzentwicklung und insgesamt verbesserten Leistungen führt.",
            ct_other2_Headline: "Steigern Sie die Mitarbeiterbindung und Motivation",
            ct_other2_Text: "Durch die Integration von Spielmechaniken in das Lernerlebnis fördert Qizify die Mitarbeiterbindung und Motivation. Mitarbeiter können Karma-Punkte durch Quizbestätigung durch Trainer oder Likes von Kollegen verdienen, was ein Gefühl von Erfolg und freundlichem Wettbewerb schafft.",
            ct_other3_Headline: "Zentralisiertes Repository relevanter Quizze für konsistentes Lernen, die für Sie relevant sind.",
            ct_other3_Text: "Quizze, die von Mitarbeitern oder Trainern erstellt werden, stehen automatisch allen anderen Benutzern zur Verfügung und fördern den Wissensaustausch und die Standardisierung von Lernmaterialien. Dies hilft Unternehmen dabei, eine kohärente Lernumgebung aufrechtzuerhalten und den nahtlosen Transfer von Wissen und Fähigkeiten zu erleichtern.",
            ct_addon1: "Die Inhaltsentwicklung wird durch KI-Assistenten unterstützt. Erstellen Sie Quizze, die für Ihr Unternehmen relevant sind, 15-mal schneller!",
            ct_addon2: "5000 vorgefertigte Quizze zu aktuellen Themen (Leadership, Cybersicherheit, Programmierung, usw.)",
            ct_addon3: "Mehr Sicherheit dank SSO-Integration",
            ct_addon4: "Auf Ihr Unternehmen zugeschnittene Anpassungen",
        }
};
