module.exports = {
  url: "https://qizify.com",
  de: {
    title: "Qizify Learning",
    description: "Qizify Learning ist eine Online-Plattform für Lernende und Lehrende, die mit studiengangsbezogenen Quizzes die Selbstvorbereitung auf Prüfungen erleichtert.",
    featuresSecureTitle: "Funktionen für Ihre Sicherheit",
    featuresSoftwareTitle: "Features zur einfachen Integration in Ihr Lehrkonzept",
    latestBlogPosts: "Letzte Blog Artikel",
    testimonials: "Studierende von acht europäischen Universitäten haben Qizify getestet und lieben es.",
    contact: "Kontakt",
    requestDemo: "Demo & Kontakt",
    contactName: "Ihr Name",
    contactMail: "Ihre E-Mail-Adresse",
    contactMessage: "Ihre Nachricht",
    contactSend: "Absenden",
    contactSuccessTitle: "Vielen Dank für Ihre Nachricht!",
    contactSuccessSubtitle: "Ihre Nachricht wurde erfolgreich übermittelt.",
    contactBookDemo: "Buchen Sie einen Demo-Termin",
    contactBookDemoSubline: "Kostenlosen Demo-Termin via Calendly.",
    contactBoxText: "Ich stimme der",
    contactBoxText2: "stimme zu, von Qizify per E-Mail kontaktiert zu werden. Ich stimme der Speicherung meiner übermittelten Daten für den erforderlichen Zeitraum zu.",
    contactPrivacyLink: "Datenschutzerklärung",
    contactAnd: "und",
    contactTermsLink: "Nutzungsbedingungen"
  },
  en: {
    title: "Qizify Learning",
    description: "Qizify Learning is an online platform for learners and lecturers that facilitates self-preparation for exams with quizzes related to a study program.",
    featuresSecureTitle: "Features for your security",
    featuresSoftwareTitle: "Features for easy integration into your educational concept",
    latestBlogPosts: "Latest blog posts",
    testimonials: "Students from nine European universities have tested Qizify and love it.",
    contact: "Contact",
    requestDemo: "Demo & contact",
    contactName: "Your name",
    contactMail: "Your email",
    contactMessage: "Your message",
    contactSend: "Send",
    contactSuccessTitle: "Thank you for your message!",
    contactSuccessSubtitle: "Your message has been sent successfully.",
    contactBookDemo: "Book a demo appointment",
    contactBookDemoSubline: "Free demo appointment via Calendly.",
    contactBoxText: "I agree to the",
    contactBoxText2: "I consent to be contacted by Qizify via email. I agree to the storage of my transmitted data for the required time.",
    contactPrivacyLink: "Privacy Policy",
    contactAnd: "and",
    contactTermsLink: "Terms of Use"
  }
}