module.exports = {
  url: "https://qizify.com",
  de: {
    title: "Qizify Learning",
    description: "Qizify Learning ist eine Online-Plattform für Lernende und Lehrende, die mit studiengangsbezogenen Quizzes die Selbstvorbereitung auf Prüfungen erleichtert.",
    featuresSecureTitle: "Funktionen für Ihre Sicherheit",
    featuresSoftwareTitle: "Features zur einfachen Integration in Ihr Lehrkonzept",
    latestBlogPosts: "Letzte Blog Artikel",
    testimonials: "Studierende von neun europäischen Universitäten haben Qizify getestet und lieben es.",
    contact: "Bestellen Sie jetzt Ihr Qizify-Paket!",
    requestDemo: "Kostenlos testen",
    contactName: "Name",
    contactCompanyName: "Hochschule / Unternehmens",
    contactMail: "E-Mail-Adresse",
    contactMessage: "Notiz",
    contactAmountOfUsers: "Vorraussichtl. Anzahl an Nutzern",
    contactNewsletter: "Newsletter: Ja, ich möchte Informationen von Qizify über deren weitere Produkte, Angebote, Neuigkeiten erhalten.",
    contactSend: "Absenden",
    contactSuccessTitle: "Vielen Dank für Ihre Nachricht!",
    contactSuccessSubtitle: "Ihre Nachricht wurde erfolgreich übermittelt.",
    contactBookDemo: "Video-Call buchen",
    contactBookDemoSubline: "Kostenlosen Demo-Termin via Calendly.",
    contactBoxText: "Ich stimme der",
    contactBoxText2: "stimme zu, von Qizify per E-Mail kontaktiert zu werden. Ich stimme der Speicherung meiner übermittelten Daten für den erforderlichen Zeitraum zu.",
    contactPrivacyLink: "Datenschutzerklärung",
    contactAnd: "und",
    contactOr: "oder",
    contactTermsLink: "Nutzungsbedingungen"
  },
  en: {
    title: "Qizify Learning",
    description: "Qizify Learning is an online platform for learners and lecturers that facilitates self-preparation for exams with quizzes related to a study program.",
    featuresSecureTitle: "Features for your security",
    featuresSoftwareTitle: "Features for easy integration into your educational concept",
    latestBlogPosts: "Latest blog posts",
    testimonials: "Students from nine European universities have tested Qizify and love it.",
    contact: "Order your Qizify package now!",
    requestDemo: "Free trial",
    contactName: "Name",
    contactCompanyName: "University / Company",
    contactMail: "Email",
    contactMessage: "Note",
    contactAmountOfUsers: "Estimated number of users",
    contactNewsletter: "Newsletter: Yes, I want to receive information from Qizify about their other products, offerings, news.",
    contactSend: "Send",
    contactSuccessTitle: "Thank you for your message!",
    contactSuccessSubtitle: "Your message has been sent successfully.",
    contactBookDemo: "Book a call",
    contactBookDemoSubline: "Free demo appointment via Calendly.",
    contactBoxText: "I agree to the",
    contactBoxText2: "I consent to be contacted by Qizify via email. I agree to the storage of my transmitted data for the required time.",
    contactPrivacyLink: "Privacy Policy",
    contactAnd: "and",
    contactOr: "or",
    contactTermsLink: "Terms of Use"
  }
}